### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Totalbug92** [zombodotcom/Zombpoe#18]
This is what happens whenever I click force refresh
![image](https://user-images.githubusercontent.com/32250965/68371855-e7198c00-013f-11ea-8c4e-0a1ca7e85eb3.png)

And I don't get any results after that.

**Comment by zombodotcom** [comment]
Resp3 is your stash data. Looks like it's not being grabbed. Did you enter your poesessid? 
I sometime have to click the button twice. Once to get poeninja data, then again to do the stash. But I usually just have to click once . This also only works with blight for right now.

**Comment by zombodotcom** [comment]
This has to do with how zombpoe grabs the data. the reason you arent getting your stash data back is probably because you have more than 48 stashes. 

This is a rate limit error, I can only grab 48 stashes every 3 minutes currently. But, I am going to add something to make sure we get all of our data without getting rate limited by the path of exile stash API. <3

**Comment by oBo125** [comment]
Using version 0.0.5 I'm getting the exact same error. I entered the session id, accountname, but when I enter my charactername, after 20 characters the name is no longer purple underlined, but red. My charactername is 23 chars long. After force refresh the same information appears as OP.

**Comment by zombodotcom** [comment]
Ohh dang I'm sorry. I'll update the input validators in a few hours. I have it set to 20 right now. I should have made it longer 

Have you tried a character name that is shorter in that league ?

**Comment by zombodotcom** [comment]
@oBo125 Also, you don't even need the character name. you can type something random in. it's more of a placeholder right now.  


We don't get character data yet, just account stash data. 
![image](https://user-images.githubusercontent.com/13477955/68535127-66eb5600-02fa-11ea-9bd9-115bd353fa94.png)

character is going to be when I add what your character is wearing pricing too.

**Comment by oBo125** [comment]
Would love to try it out, but still not working for me at version 0.0.6. My accountname is an email address, is this perhaps causing errors?

edit: I double checked if the path of exile website was up (since it says 'PoE might be down') and the pathofexile.com website was up at the time of trying, even though now it is actually offline for maintenance. Will try again later today.

![zombpoe](https://user-images.githubusercontent.com/57561562/68915619-2446d500-0763-11ea-813e-3f08b5931a36.jpg)

**Comment by zombodotcom** [comment]
im going to have to make an email and check. mine is through stream. How do people message you in game without an account name?

**Comment by oBo125** [comment]
My bad. I do have an accountname...

First time I see it. Sorry. It's working now.

<notifications@github.com>

**Comment by zombodotcom** [comment]
I'll look at it some more tomorrow.

**Comment by zombodotcom** [comment]
I'll make another Poe account from email today without steam and see what I can do. Sorry it's not working right just yet for you

**Comment by Totalbug92** [comment]
Yeh, I have way too many stash tabs :P 
So that was probably it

**Comment by zombodotcom** [comment]
This has to deal with your account name or something else. Ill be closing for now

in your browser if you are logged into pathofexile on the browser

type in this
[Character Names for your account](https://www.pathofexile.com/character-window/get-characters?accountName=qqazraelz)

the link is just 
https://www.pathofexile.com/character-window/get-characters?accountName=**youraccountname**

it should show u have toons. 
you can also run  https://www.pathofexile.com/character-window/get-stash-items?league=Blight&accountName=**youraccountname**&tabs=1&tabIndex=1

and it should show you a request that has your tab names in "n":<tabname!>

please comment here if you have more issues. ill try and help. or the discord
